# Generated by Django 4.2.4 on 2023-08-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Full pack', 'full'), ('Free pack', 'free')], default='Free pack', max_length=30),
        ),
    ]
