# Generated by Django 4.2.4 on 2023-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.CharField(choices=[('Only read', 'user'), ('Redaction', 'redactor')], default='Only read', max_length=30),
        ),
    ]
